### ISSUE TITLE
[BUG] How to close "the POST https://analytics.pyroscope.io"

### ISSUE THREAD

**Issue by oeular** [pyroscope-io/pyroscope#1132]
My app cannot access the site "analytics.pyroscope.io", so I want to close the request at the best to make my app running in normal.

**Comment by oeular** [comment]
ping @petethepig, I need your help.

**Comment by oeular** [comment]
I have fixed. Thank you.

**Comment by eh-am** [comment]
Just for documentation purposes, there's a [`--analytics-opt-out` flag](https://github.com/pyroscope-io/pyroscope/blob/main/pkg/config/config.go#L100). That's what you used, right? @oeular

**Comment by oeular** [comment]
Actually, in the codes the default value is true, not false. 
It is a need to config the analytics-opt-out to be false in the config file.

**Comment by Rperry2174** [comment]
Glad you got it figured out @oeular you can also see more information about that here: https://pyroscope.io/docs/server-configuration/! We do have it this way by default in order to improve the product and understand which features are most important to those using Pyroscope. 

Going to close as this is intended behavior, but if you have any questions feel free to reach out here or in our [slack channel](https://pyroscope.io/slack).
