### ISSUE TITLE
How to run/debug pyroscope server on local machine 

### ISSUE THREAD

**Issue by Jun10ng** [pyroscope-io/pyroscope#1225]
Hi team, 
I want to debug pyroscope server on my PC.
Is there any "IDE configuration" or "bash script" to run it? I only found the way of running on docker at the website.

Thanks.

**Comment by eh-am** [comment]
Hey! Depends what you mean by "debug":

* If you want to be able to modify code, we recommend the following flow https://pyroscope.io/docs/developer-guide/ 
  * Notice that you can run `make build` instead of `make dev`, which will build a binary.
* If you just want to just run the binary (without setting up a local dev stack), you can download it here https://pyroscope.io/downloads/ (notice that you have to check "Standalone Binaries")

All that being said, is there any specific problem you are having that is making you have to run locally? If possible let us know!

**Comment by Jun10ng** [comment]
Thank for your reply @eh-am 

I mean "debug" is setting some breakpoints to figure out how pyroscope server is running.

Any way I have "debug" it successfully with Goland IDE, can I add my way on this [page](https://pyroscope.io/docs/developer-guide/) , under VS code selection?

**Comment by eh-am** [comment]
@Jun10ng 
Oh of course, sorry for my brain fart!

>can I add my way on this [page](https://pyroscope.io/docs/developer-guide/) , under VS code selection?
Definitely! We store docs in a different repository, though: https://github.com/pyroscope-io/docs/blob/main/docs/developer-guide.mdx
