### ISSUE TITLE
Deploy on K8S profiling got error 

### ISSUE THREAD

**Issue by TommyVV** [pyroscope-io/pyroscope#1523]
Dear pyroscope team :
I want to profiling our dotnet 6.0 app ,but When I deploy on our K8S cluster, we got some errors : 
```
time="2022-09-16T22:50:13.002224" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n, 1 messages skipped due to throttling" file=" agent/session.go:283"
time="2022-09-16T22:50:33.002991" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n, 1 messages skipped due to throttling" file=" agent/session.go:283"
time="2022-09-16T22:50:53.003221" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n, 1 messages skipped due to throttling" file=" agent/session.go:283"
time="2022-09-16T22:51:13.002756" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n, 1 messages skipped due to throttling" file=" agent/session.go:283"
time="2022-09-16T22:51:23.003215" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n" file=" agent/session.go:285"
time="2022-09-16T22:51:43.001850" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n, 1 messages skipped due to throttling" file=" agent/session.go:283"
time="2022-09-16T22:51:53.002841" level=error msg="error taking snapshot: 1 error occurred:\n\t* dial unix : missing address\n\n" file=" agent/session.go:285"
```
our docker file :
```
FROM xxx/base/dotnet/core/aspnet:6.0-alpine
WORKDIR /app
COPY publish/ .
COPY --from=xxxr/pyroscope/pyroscope:0.28.1 /usr/bin/pyroscope /usr/bin/pyroscope
ENV PYROSCOPE_SPY_NAME=dotnetspy
ENV PYROSCOPE_APPLICATION_NAME=MyApp
ENV PYROSCOPE_SERVER_ADDRESS=http://pyroscope.xxxx.lt
ENV PYROSCOPE_LOG_LEVEL=debug

RUN adduser --disabled-password --gecos --quiet pyroscope
USER pyroscope
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE  8080
CMD ["pyroscope", "exec", "dotnet", "MyApp.dll"]
```
But When I deploy windows WSL2, it's works ,I dont know why , I guess maybe is our securitycontext setting ? 
our k8s yaml SecurityContext :
![image](https://user-images.githubusercontent.com/26179831/190842971-86023fe4-447a-4519-b718-e3de42f7a264.png)

**Comment by kolesnikovae** [comment]
Hello @TommyVV. Thank you for reporting the issue!

When a .NET application starts, it creates a special diagnostic protocol socket for communications with debugging tools (such as **dotnet-trace**) in the temp directory (`/tmp` by default), pyroscope leverages this mechanism as well. The error you encountered is caused by inability of pyroscope agent to discover the unix domain socket created by the .NET application: https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#transport.

I suspect that `securityContext` is indeed preventing pyroscope to connect to the application runtime, however, I don't know in what exactly way. Could you please ensure that /tmp (or `TMPDIR`, if is overridden) is writable within the container for user `10001` and it contains the socket named like `dotnet-diagnostic-{PID}`? Also, could you try to re-build the image without the user by removing these lines?
```
RUN adduser --disabled-password --gecos --quiet pyroscope
USER pyroscope
```

I think that we could try to run pyroscope agent as [a sidecar](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostics-in-containers) that would share /tmp directory with the target application. Unfortunately, we don't have a ready to use example as of now (we will prepare it soon!) but you can find [this example setup](https://github.com/pyroscope-io/pyroscope/issues/888#issue-1148430614) helpful.

**Comment by TommyVV** [comment]
> Hello @TommyVV. Thank you for reporting the issue!
> 
> When a .NET application starts, it creates a special diagnostic protocol socket for communications with debugging tools (such as **dotnet-trace**) in the temp directory (`/tmp` by default), pyroscope leverages this mechanism as well. The error you encountered is caused by inability of pyroscope agent to discover the unix domain socket created by the .NET application: https://github.com/dotnet/diagnostics/blob/main/documentation/design-docs/ipc-protocol.md#transport.
> 
> I suspect that `securityContext` is indeed preventing pyroscope to connect to the application runtime, however, I don't know in what exactly way. Could you please ensure that /tmp (or `TMPDIR`, if is overridden) is writable within the container for user `10001` and it contains the socket named like `dotnet-diagnostic-{PID}`? Also, could you try to re-build the image without the user by removing these lines?
> 
> ```
> RUN adduser --disabled-password --gecos --quiet pyroscope
> USER pyroscope
> ```
> 
> I think that we could try to run pyroscope agent as [a sidecar](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/diagnostics-in-containers) that would share /tmp directory with the target application. Unfortunately, we don't have a ready to use example as of now (we will prepare it soon!) but you can find [this example setup](https://github.com/pyroscope-io/pyroscope/issues/888#issue-1148430614) helpful.

Hi @kolesnikovae , thank you for your reply

1. I delete these lines, but it still doesn't work
```
RUN adduser --disabled-password --gecos --quiet pyroscope
USER pyroscope
```
2.I have reconfirmed that /tmp is writable
3.I looked at socket and it doesn't have a name like `dotnet-diagnostic-{PID}`, but in wsl2

I'm looking forward to the `sidecar` example

**Comment by TommyVV** [comment]
Finally I solved the problem, I added an env `COMPlus_EnableDiagnostics : 1` to the container, then it worked.   thank you very much.

**Comment by kolesnikovae** [comment]
Thank you so much @TommyVV for posting the solution!

I'm wondering if the option is defined in the **runtimeconfig.json**. We currently assume that the runtime is configured with default settings which might be a wrong approach (`COMPlus_EnableDiagnostics` is set to 1 [by default](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/debugging-profiling#enable-diagnostics) which usually causes problems when running in read-only environments and therefore often disabled). I think we need to update the documentation to explicitly mention the restriction and describe ways to circumvent it
