### ISSUE TITLE
Flamegraph in exemplars page doesn't span 100% width

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#1724]
![image](https://user-images.githubusercontent.com/6951209/202255277-5d379357-3856-426c-91d6-dbd067c9f0c6.png)

Compared with single view:
![image](https://user-images.githubusercontent.com/6951209/202255422-226b0d4e-e658-4a54-a66b-20331c6f055c.png)

**Comment by Rperry2174** [comment]
![image](https://user-images.githubusercontent.com/23323466/202269316-a51feb55-d0b2-4c27-adee-783211cbba23.png)

**Comment by dogfrogfog** [comment]
yes, I think the problem here may be with the [subtract](https://github.com/pyroscope-io/pyroscope/blob/main/packages/pyroscope-flamegraph/src/convert/subtract.ts#L69) function. We pass the result of that function to [diffTwoProfiles](https://github.com/pyroscope-io/pyroscope/blob/main/packages/pyroscope-flamegraph/src/convert/diffTwoProfiles.ts) and if input numbers are incorrect it reflects on diff profile 

cc @Rperry2174 @eh-am @petethepig
