### ISSUE TITLE
Separate 'comparison' endpoint from 'diff' endpoint

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope#321]
In #289 we added Diff rendering to be able to show the diff between two flamegraphs. Currently this diff is consolidated into one endpoint. This will become harder to maintain over time. See this comment for more information:

https://github.com/pyroscope-io/pyroscope/pull/289#discussion_r675988905

> It may be way more convenient to introduce a new endpoint. Let's say, render-diff (or query-diff), that would accept POST with the following payload:
> 
> type RenderDiffParams struct {
> 	Format      string
> 	MaxNodes    int
> 	Left, Right RenderTreeParams
> }
> 
> type RenderTreeParams struct {
> 	From  string
> 	To    string
> 	Query *string
> 	Name  *string
> }

**Comment by yashrsharma44** [comment]
As far as I understand from reading the codebase and the comments - 
* Comparison Endpoint - Uses `render/` API endpoint for rendering the table
* Diff Endpoint - Uses `render-diff/` API endpoint for rendering the diff between to tables.

Since both the views use different endpoints, we dont need to break down the API endpoints, as it is already done( For comparison page we have `render` endpoint, while for Diff page, we have `render-diff` page.

What are the objectives of this issue then?
* I think that we can use `POST` requests as compared to `GET` as suggested out here - https://github.com/pyroscope-io/pyroscope/pull/289#discussion_r675988905
* Anything else am I missing out in this issue requirement?

**Comment by kolesnikovae** [comment]
@yashrsharma44 That's right - `render-diff` was implemented in #289.

> I think that we can use POST requests as compared to GET as suggested out here 

Sounds good to me. I think we could add support for `POST` with the specified payload structure and then optionally deprecate `GET`. Given that this is not a public API, I believe it won't cause any issues: the only external client is Grafana panel plugin, which does not support diff view yet AFAIK.

**Comment by Rperry2174** [comment]
I agree with @kolesnikovae and can confirm we don't need to worry about Grafana plugin diff view yet

**Comment by yashrsharma44** [comment]
Sure, thanks for the clarification 💯
