### ISSUE TITLE
Make prometheus metrics follow naming conventions

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope#332]
Link to naming conventions: https://prometheus.io/docs/practices/naming/

Minimally we should do things like:
* [ ] add `pyroscope_` prefix
* [ ] add proper suffixes, like `_total` or `_bytes`
* [ ] add tags where appropriate, e.g for badger metrics we should have `trees` and `segments` be tags, not parts of the name

---

This would also be a good time to get rid of `metrics` package I think.

---

After we update the names we should also update these dashboards:
* [ ] the one in `./benchmark`
* [ ] the one in `./examples/grafana-integration`
* [ ] the one on grafana website

**Comment by eh-am** [comment]
BTW

would be nice to add this prometheus metrics linter
https://github.com/yeya24/promlinter

it can be integrated with golangci-lint (yeah I know we are using revive, although it can be added to golangci-lint, see https://github.com/mgechev/revive#golangci-lint)

but anyway, to get the linter working it seems we would need to change/remove the `metrics` package, since the linter seems to expect a certain format (https://github.com/yeya24/promlinter/blob/master/promlinter.go#L191), plus having greppable metric names is always a good idea :)

**Comment by petethepig** [comment]
@eh-am this is a great idea, I think we should remove metrics package and then we can add the linter

**Comment by petethepig** [comment]
Closing because this was implemented a while ago
