### ISSUE TITLE
Diff view is not colorblind friendly

### ISSUE THREAD

**Issue by lizthegrey** [pyroscope-io/pyroscope#657]
Use of red and green is considered problematic -- https://webaim.org/articles/visual/colorblind

**Comment by lizthegrey** [comment]
Relates to #24

**Comment by petethepig** [comment]
Great point, thanks for bringing this up! That's another good reason to prioritize #24 

Another thing I'm thinking is when we work on this we might want to look closer at existing colors we use to distinguish between packages and see if we can tweak them to be more universally distinguishable.

**Comment by Rperry2174** [comment]
Another example for color palettes https://venngage.com/blog/color-blind-friendly-palette/#4

**Comment by Rperry2174** [comment]
For this I think the first step is to slightly refactor the code to take arbitrary colors as inputs. For the v1 of this, and for simplicity, we should just focus on the diff view and then potentially expand out in into the other views later. 

Right now the red and green colors are hardcoded [here](https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/FlameGraph/FlameGraphComponent/color.ts#L34-L35)

We should start by un-hardcoding these values and instead passing them into a function that then renders both the flamegraph and the legend. 

Then we should create a couple different color options in a dropdown that when selected will change the diff view to be rendered with the new colors (similar to picture below with just two colors per selection):
![image](https://user-images.githubusercontent.com/23323466/147499269-24fe4af7-de04-4f4f-b5d6-12434f271cb7.png)

Eventually once #591 is completed we can also save these preferences for users

**Comment by eh-am** [comment]
@Rperry2174 

Few points I am thinking
* this is not strictly for the comparison diff
* for v1 we can have a simple dropdown (as you pointed) with 2 modes: Default | ColorBind. It's a bit reductive yes (as you pointed with the palettes above), but it's a good start.
* that however makes the toolbar more bloated, which I guess requires us to create versions of the buttons with icons only? That would require us to add a tooltip component (otherwise how am I supposed to know what this button means)?
* suffice to say, tooltips should also be a11y friendly.
* code wise, I'm thinking accepting a custom ColorRenderer or similar here https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/FlameGraph/FlameGraphComponent/Flamegraph_render.ts#L72 , which implements `getColor` https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/FlameGraph/FlameGraphComponent/Flamegraph_render.ts#L225-L246

**Comment by Rperry2174** [comment]
This is now included in the most recent version! More coming soon in #746
