### ISSUE TITLE
failed to get update the latest version

### ISSUE THREAD

**Issue by seth-shi** [pyroscope-io/pyroscope#882]
```
level=warning msg="failed to get update the latest version" file=" util/updates/updates.go:54" error="Get \"https://pyroscope.io/latest-version.json\": dial tcp: lookup pyroscope.io on 127.0.0.11:53: read udp 127.0.0.1:54048->127.0.0.11:53: i/o timeout"
```

Running with Docker, I think this issue should be a warning, not a crash

**Comment by kolesnikovae** [comment]
Thank you for reporting the issue @seth-shi! Just to clarify: does it cause the container to crash? I'm asking because it should work according to your suggestion – in case if the latest version can't be fetched, a warning log message is written and the server continues to run:
https://github.com/pyroscope-io/pyroscope/blob/83384865e54c494b99d36819b7e3b347448d5729/pkg/util/updates/updates.go#L48-L60

Could you please clarify the server version?

**Comment by seth-shi** [comment]
Because when my container stops running, the last log is this.  Now let me revisit whether it's something else.  
Maybe the process was killed due to too much memory usage. I have limited the memory usage of the container, and I will continue to feedback if there is no problem

**Comment by kong62** [comment]
how disable check update?
