### ISSUE TITLE
Remove non-empty 'Full name' and 'email' requirement

### ISSUE THREAD

**Issue by eh-am** [pyroscope-io/pyroscope#907]
In settings page the frontend makes full name and email to be required, but that's not really required from backend perspective. We should relax these requirements in the frontend.

![Peek 2022-03-02 11-13](https://user-images.githubusercontent.com/6951209/156378632-a85a2ee0-b005-4a0f-82fc-42ae9c27e9f8.gif)

**Comment by webstradev** [comment]
Started to take a look at this, unsure why the full name is behaving as a required field because out of the three it looks like only Username and Email have a required attribute. But as I said, I will take a look.

![image](https://user-images.githubusercontent.com/82543732/156444148-f7ba2a66-5d3f-4276-8ff8-ce0140acc057.png)

**Comment by eh-am** [comment]
Closed by https://github.com/pyroscope-io/pyroscope/pull/912
