### ISSUE TITLE
web-postinstall-sh not found

### ISSUE THREAD

**Issue by webstradev** [pyroscope-io/pyroscope#910]
I'm trying to set up my development environment so I can get my feet wet with a few of the outstanding issues.
I ran through the installation steps as provided on your website [here](https://pyroscope.io/docs/developer-guide/#windows).

`make install-dev-tools` finishes successfully, during the `ENABLED_SPIES=none make dev` I get an error after the yarn build completes and it tries to run the `web-postinstall-sh` file.

The specific error is `/bin/sh: 1: ./scripts/web-postinstall.sh: not found`:
![image](https://user-images.githubusercontent.com/82543732/156456112-2153af92-5669-4105-8da2-589c90e9ad4e.png)

Weirdly enough that file is definitely there, I can click on it in the error and it takes me straight to it.

Any ides or further information needed let me know.

**Comment by eh-am** [comment]
Hey, thank you for raising this issue!

What OS are you running? Windows right?
I think it's happening because you don't have `sh` under your PATH. 

I guess we should just rewrite that script to use node instead.

As a workaround, you can just remove that line from `package.json` (https://github.com/pyroscope-io/pyroscope/blob/main/package.json#L16)

**Comment by webstradev** [comment]
The workaround worked thanks
